package indy;

public class Constants {
    public static final int LAWN_WIDTH = 100;
    public static final int SCENE_WIDTH = LAWN_WIDTH * 10;
    public static final int SCENE_HEIGHT = LAWN_WIDTH * 7;
    public static final int DISPLAY_SCENE_WIDTH = Constants.SCENE_WIDTH + 20;
    public static final int DISPLAY_SCENE_HEIGHT = Constants.SCENE_HEIGHT + 30;
    public static final int LAWN_ROWS = 5;
    public static final int LAWN_COLUMN = 9;
    public static final int SEED_PACKET_NUMBER = 5;
    public static final int INITIAL_SUN = 500;
    public static final int SUN_COST = 25;
    public static final int PEA_RADIUS = 10;
    public static final int ZOMBIE_WIDTH = 50;
    public static final int SUN_RADIUS = 20;
    public static final int PEASHOOTER_COST = 100;
    public static final int PEASHOOTER_HEALTH = 4000;
    public static final int PEASHOOTER_NUMBER = 1;
    public static final int SUNFLOWER_COST = 50;
    public static final int SUNFLOWER_HEALTH = 2000;
    public static final int SUNFLOWER_NUMBER = 2;
    public static final int CHERRYBOMB_COST = 150;
    public static final int CHERRYBOMB_NUMBER = 3;
    public static final int WALNUT_COST = 50;
    public static final int WALNUT_HEALTH = 30000;
    public static final int WALNUT_NUMBER = 4;
    public static final int CATTAIL_COST = 200;
    public static final int CATTAIL_HEALTH = 4000;
    public static final int CATTAIL_NUMBER = 5;
    public static final int LEVEL_ONE_RATIO = 8000;
    public static final int LEVEL_ONE_COUNT = 30;
    public static final int LEVEL_TWO_RATIO = 6000;
    public static final int LEVEL_TWO_COUNT = 40;
    public static final int LEVEL_THREE_RATIO = 4000;
    public static final int LEVEL_THREE_COUNT = 50;
    public static final int LEVEL_FOUR_RATIO = 2000;
    public static final int LEVEL_FOUR_COUNT = 60;
    public static final int NORMAL_ZOMBIE_HEALTH = 4;
    public static final int CONE_HEAD_ZOMBIE_HEALTH = 8;
    public static final int BUCKET_HEAD_ZOMBIE_HEALTH = 12;
}
